export const styles = {
	container: {
		maxWidth: 900,
		margin: "2rem auto",
		display: "grid",
		gap: 24,
		padding: "0 1rem", // Added responsive padding
	},
	card: {
		border: "1px solid #e2e8f0",
		boxShadow: "0 2px 8px #f1f5f9",
		transition: "transform 0.2s ease, box-shadow 0.2s ease",
		cursor: "pointer",
	},
	cardHover: {
		transform: "translateY(-2px)",
		boxShadow: "0 4px 16px #e2e8f0",
	},
	cardContent: {
		display: "flex",
		alignItems: "flex-start",
		gap: 16,
	},
	postImage: {
		width: 60,
		height: 60,
		objectFit: "cover",
		borderRadius: 8,
		border: "2px solid #d1d5db",
		flexShrink: 0,
	},
	postImageModal: {
		width: 80,
		height: 80,
		objectFit: "cover",
		borderRadius: 8,
		border: "2px solid #d1d5db",
		flexShrink: 0,
	},
	postTitle: {
		margin: 0,
		fontSize: "1.2rem",
		color: "#1e293b",
		lineHeight: 1.3,
	},
	postTitleModal: {
		margin: 0,
		fontSize: "1.5rem",
		color: "#1e293b",
		lineHeight: 1.3,
	},
	meta: {
		color: "#475569",
		fontSize: 13,
		marginRight: 18,
	},
	value: {
		color: "#0f172a",
		fontWeight: 500,
	},
	featured: {
		background: "linear-gradient(90deg,#6366f1 30%,#00c9a7 100%)",
		color: "white",
		borderRadius: "6px",
		padding: "2px 10px",
		marginLeft: 8,
		fontWeight: 500,
		fontSize: 13,
		textShadow: "0 1px 6px #1112",
	},
	label: {
		background: "#f0f0f8",
		color: "#333",
		padding: "2px 8px",
		borderRadius: "8px",
		marginRight: 8,
		fontSize: 12,
		fontWeight: 500,
		display: "inline-block",
	},
	tag: {
		background: "#dcfce7",
		color: "#166534",
		padding: "2px 8px",
		borderRadius: "8px",
		marginRight: 8,
		fontSize: 12,
		fontWeight: 500,
		display: "inline-block",
	},
	content: {
		marginTop: 12,
		color: "#334155",
		lineHeight: 1.7,
		fontSize: 15,
	},
	stats: {
		marginTop: 12,
		display: "flex",
		gap: "1.2em",
		fontSize: 14,
		color: "#475569",
	},
	button: {
		marginTop: 14,
		padding: "8px 18px",
		background: "#6366f1",
		color: "#fff",
		border: "none",
		borderRadius: 6,
		cursor: "pointer",
		fontWeight: 500,
		fontSize: 14,
		transition: "background-color 0.2s ease",
	},
	buttonHover: {
		backgroundColor: "#4f46e5",
	},
	modalOverlay: {
		position: "fixed",
		top: 0,
		left: 0,
		right: 0,
		bottom: 0,
		background: "rgba(0,0,0,0.5)",
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		zIndex: 1000,
		padding: "1rem",
	},
	modalContent: {
		background: "#fff",
		borderRadius: 12,
		boxShadow: "0 8px 32px rgba(0,0,0,0.12)",
		maxWidth: 600,
		width: "100%",
		maxHeight: "90vh",
		overflowY: "auto",
		padding: 32,
		position: "relative",
	},
	closeButton: {
		position: "absolute",
		top: 16,
		right: 16,
		background: "#e11d48",
		color: "#fff",
		border: "none",
		borderRadius: 6,
		padding: "6px 12px",
		cursor: "pointer",
		fontWeight: 500,
		fontSize: 14,
		transition: "background-color 0.2s ease",
	},
	closeButtonHover: {
		backgroundColor: "#be185d",
	},
};
